### PR TITLE
Add transformWsUrl option, and fix some travis/browser test issues

### LINKED ISSUE #535: Add an urlSigner (func) option to connect to pass to the ws streambuilder
For AWS IoT wss connections urls require Sigv4 signing. These urls seemingly expire, so eventually reconnect doesn't work and you need a fresh signature. 

You can see here usage of an old version of mqtt.js: https://github.com/aws/aws-iot-device-sdk-js/blob/master/device/index.js#L502-L521

I'm using mqtt.js 2.x directly and my own url signer implementation. 

I will possibly get around to a pull request but first would like to see how do people feel about adding an `urlSigner` function to the connection options, passed along to the stream builder[s]?

### LINKED ISSUE #537: Travis build script is broken
> - test $SAUCE_USERNAME && npm run sauce-test || echo 'not running on saucelabs'

Note the above will always return 0 yes?

eg.
```zsh
➜  MQTT.js git:(master) ✗ python -c "import sys; sys.exit(1)"
➜  MQTT.js git:(master) ✗ echo $?
1
➜  MQTT.js git:(master) ✗ export SAUCE_USERNAME=wink
➜  MQTT.js git:(master) ✗ test $SAUCE_USERNAME && python -c "import sys; sys.exit(1)" || echo 'not running on saucelabs'
not running on saucelabs
➜  MQTT.js git:(master) ✗ echo $?
0
```
Please see: https://travis-ci.org/mqttjs/MQTT.js/jobs/196752870#L842-L870

### LINKED ISSUE #538: Browser tests broken
re: #537 

See saucelabs results:
image

I tried running `npm run browser-test` locally, and I got some errors, due to this:
https://github.com/mqttjs/MQTT.js/blob/master/test/browser/server.js#L106-L107

```js
function start (startPort, done) {
  var server = http.createServer()
  var wss = new WebSocketServer({server: server})

  wss.on('connection', function (ws) {
    var stream, connection
    if (ws.protocol !== 'mqttv3.1') {
      return ws.end()
    }
```

I'm not sure if it's due to some of my local copy refactoring, but one thing is for sure, the `ws` object has no end property. It *does* have a close method.

### PR DESCRIPTION
**Pull request by sublimator**
Testing Travis and saucelabs

Fixes #538 
Fixes #535 
Fixes #537

### CODE REVIEW

**Comment by sublimator** [comment]
So I see there's a pre commit hook (specified in package.json, didn't know you could do that :) ) that runs the `test` script but not `browser-test`, which off course seems to be because zuul just hangs when the --local option is passed. It would be nice if that project had some kind of ability to `process.exit( passed ? 0 :  1)`.   

I guess at the least we could add `browser-build` to the pre-commit list of scripts?

File: lib/connect/ws.js [hunk 1]
```diff
@@ -1,71 +1,78 @@
...
-  // for Web Workers! P.S: typeof(document) !== undefined may be becoming the faster one these days.
-  if (typeof (document) !== 'undefined') {
-    parsed = _URL.parse(document.URL)
-  } else {
+function buildBuilderBrowser (client, opts) {
+  // For Web Workers!
+  // P.S: typeof(document) === undefined may be becoming the faster one these days.
+  // TOOD: faster than what??
+  if (typeof (document) === 'undefined') {
+    // TODO: Why doesn't this check for `host` ? re: `Specify host manually.`
```
Comment (mcollina) [inline lib/connect/ws.js]: why those todos?

cc @sandro-k

**Comment by mcollina** [comment]
Good job on the testing side, thanks!!!!!!

**Comment by sublimator** [comment]
Todos r questions to you guys and reminders to myself! I can remove if/b4 u
merge

**Comment by sublimator** [comment]
Will add docs/strip todos after lunch

File: lib/connect/ws.js (hunk 1 above)
Comment (sandro-k) [inline lib/connect/ws.js]: I am not sure what the question is on line 
```
71 // TODO: Why doesn't this check for `host` ? re: `Specify host manually.`
```

**Comment by sublimator** [comment]
re: TODO: Why doesn't this check for `host` ? re: `Specify host manually.`

look at the old code:
```js
function buildBuilderBrowser (mqttClient, opts) {
  var wsOpt = {
    protocol: 'mqtt'
  }
  var url
  var parsed

  // for Web Workers! P.S: typeof(document) !== undefined may be becoming the faster one these days.
  if (typeof (document) !== 'undefined') {
    parsed = _URL.parse(document.URL)
  } else {
    throw new Error('Could not determine host. Specify host manually.')
  }
```

The code doesn't even give the user a chance to specify a host manually, no?

**Comment by sublimator** [comment]
I'm not quite sure about the implications of WebWorkers and browsers but it seems like the old error message indicated that you ought to be able to specify a host manually somehow? 

What should the correct behaviour (ou showing my Aussienessness lelz) be? Should it only throw an error if there's not enough information in the `opts` to piece together an url?

**Comment by sublimator** [comment]
> I'm more keen on passing a function to connect that will return the URL (or call a callback with an URL).

My thoughts on that:

If you passed in solely a function, it would return a fully signed url, and then as the code stands, it would be parsed, in the connect function, which it must do, due to having to route to the corresponding stream builders for the appropriate protocol. 

Then later, inside the stream builder, you would need logic to check if there's an url builder function and either run that, or use the current logic to build the url from the `options`. For the first connection, this would mean running the url builder function twice, once for the connect protocols[url.parse(urlBuilder())] routing, and then again inside the stream builder. Or add some convolution to avoid this.

I guess you could specify the protocol manually in the connect options and bypass this need: `{protocol: 'wss', url: urlBuilder()}` ?

Anyway, I think this is an efficient/pragmatic and reasonably non-invasive way of solving the issue, as the transformUrl function gets passed the url/options/client and can use either the url or the already parsed components, in the options, and check any possibly relevant client state.

I'm a little fuzzy on how the urls are used by the other protocols, but it seems it's nothing other than a convenient way of expressing domain/ip/port etc, whereas with WebSockets, the url is actually transported over the wire. Correct me if I'm wrong there.

**Comment by sandro-k** [comment]
You check works just fine..  Currently I am creating the `document` object before MQTT.js is running [See L25](https://github.com/mqttjs/mqtt-worker/blob/master/mqttWorker.js#L25). Ideally it should be possible to pass this option to MQTT.js.

**Comment by mcollina** [comment]
> Anyway, I think this is an efficient/pragmatic and reasonably non-invasive way of solving the issue, as the transformUrl function gets passed the url/options/client and can use either the url or the already parsed components, in the options, and check any possibly relevant client state.

Agreed, let's try to get this in then.

Would you mind to adding the docs?

**Comment by sublimator** [comment]
@sandro-k 

I'm still confused. Should it only parse the document.URL and throw an error if it cant if there's not enough information in the `opts` to piece together an url?

**Comment by sublimator** [comment]
Btw, this comment here seems stale, https://github.com/mqttjs/mqtt-worker/blob/master/mqttWorker.js#L23-L25, the url is passed in as the first arg no?

**Comment by sublimator** [comment]
```js
function buildBuilderBrowser (client, opts) {
  if (!opts.hostname) {
    opts.hostname = opts.host
  }

  if (!opts.hostname) {
    if (typeof (document) === 'undefined') {
      throw new Error('Could not determine host. Specify host manually.')
    }
    var parsed = urlModule.parse(document.URL)
    opts.hostname = parsed.hostname

    if (!opts.port) {
      opts.port = parsed.port
    }
  }
  return createWebSocket(client, opts)
}
```

This seems like the correct logic that would be inline with the Error string

**Comment by sandro-k** [comment]
@sublimator Yes you are correct.. looks very clean.

**Comment by sublimator** [comment]
@mcollina I added draft @ docs

@sandro-k  I removed the comment about webworkers, can you provide me with an update one to add?

File: README.md [hunk 2]
```diff
@@ -212,6 +235,7 @@ the `connect` event. Typically a `net.Socket`.
     * `payload`: the message to publish
     * `qos`: the QoS
     * `retain`: the retain flag
+  * `transformUrl` : optional `(url, options, client) => url` function which can be used to implement signed urls which may expire, and cause troubles upon reconnect.
```
Comment (mcollina) [inline README.md]: this needs to be specified that is for websocket only.

File: README.md [hunk 3]
```diff
@@ -104,6 +105,28 @@ run the example.
 
 to use MQTT.js in the browser see the [browserify](#browserify) section
 
+<a name="signedurls"></a>
+## Signed Urls
```
Comment (mcollina) [inline README.md]: can you move it after the `API`?

**Comment by sublimator** [comment]
@mcollina 

I added codecov.io, it's really simple to set up, though of course, you'd have to do that yourself. You  can have a browse here: https://codecov.io/gh/sublimator/MQTT.js/src/d3a09f051f16459985d7c70fb64d497324395cd4/lib/connect/ws.js

File: lib/connect/ws.js [hunk 4]
```diff
@@ -1,106 +1,89 @@
...
+}
 
+function buildBuilderBrowser (client, opts) {
   if (!opts.hostname) {
     opts.hostname = opts.host
   }
 
   if (!opts.hostname) {
+    if (typeof (document) === 'undefined') {
+      throw new Error('Could not determine host. Specify host manually.')
```
Comment (sandro-k) [inline lib/connect/ws.js]: // Throwing an error in a Web Worker if no hostname is given, because we can not determann the hostname automatically. If connecting to localhost, please supply the hostname as an argument.

**Comment by sublimator** [comment]
Heh, pretty slick, it's already got some info: https://codecov.io/gh/mqttjs/MQTT.js/src/262f872c997af410376660d238d8b92e00ce5e32/mqtt.js

But it's causing the builds to fail because there's no base commit to compare coverage to. I think you can set the tolerance, if you have repo rights and login via github. Probably easiest to just check the travis result, which seems to have passed and then once a build is triggered for master, the base should be set. I think ....

**Comment by sublimator** [comment]
@sandro-k Why can't we just default to localhost in webworkers?

**Comment by sublimator** [comment]
I'm completely unfamiliar with web workers

**Comment by sandro-k** [comment]
No I would not do that.. the line ` var parsed = urlModule.parse(document.URL)` basically connects to the current hostname on the same port via Websockets. I don't even know a good usecase for hat behavior. On a Web Worker it would be even more confusing having the site at "https://footbar" and suddenly connecting Websockets to "http://localhost"...

**Comment by sublimator** [comment]
Ok, makes sense :)

**Comment by sublimator** [comment]
*@mcollina should I put the Signed WebSocket Urls section inside the
browser section?*

**Comment by mcollina** [comment]
@sublimator yes, move the example at the top inside the browser section.

**Comment by sublimator** [comment]
Updated and pushed. Sorry, fell asleep!

File: README.md [hunk 5]
```diff
@@ -212,6 +214,9 @@ the `connect` event. Typically a `net.Socket`.
     * `payload`: the message to publish
     * `qos`: the QoS
     * `retain`: the retain flag
+  * `transformWsUrl` : optional `(url, options, client) => url` function
+        For wss/wss protocols only. Can be used to implement resigning expired
```
Comment (mcollina) [inline README.md]: this should read `ws/wss`

Comment (sublimator) [inline README.md]: oops

Comment (sublimator) [inline README.md]: pushed fix
