### PR TITLE
fix: keepalive issues

### LINKED ISSUE #1727: After mqtt client is reconnected, it is unable to continue publishing message
Hi there,

I am using the latest version of mqttjs (5.1.3) and this issue happens in old versions as well.

In my app, I received the offline event even when the mosquitto MQTT broker is up and running. After the mqttjs client goes through the process of offline -> closed -> reconnect -> connected. The mqttjs client can no longer publish messages again.

Is there a workaround?

app log:
image

mqtt broker log:
image

### PR DESCRIPTION
**Pull request by robertsLando**
Actually keepalive is shifted every time a packet is written to stream. This is wrong as this doesn't mean the stream is up and in cases where there is a constant publish the keepalive never triggers as is keeps being shifted without closing the client.

With this PR we ensure that the keep alive timer is shifted only when we receive control packets as defined in specs: https://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Ref363645900

Fixes #1727

### CODE REVIEW

File: src/lib/client.ts [hunk 1]
```diff
@@ -1924,9 +1918,6 @@ export default class MqttClient extends TypedEventEmitter<MqttClientEventCallbac
 
 		this.emit('packetsend', packet)
 
-		// When writing a packet, reschedule the ping timer
-		this._shiftPingInterval()
```
Comment (robertsLando) [inline src/lib/client.ts:1928]: The root cause of the problem

**Review by mcollina — DISMISSED** [review]
lgtm
